"on":
    push:
        branches:
            - opencode-remote-voice
name: Deploy to apn-relay
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: apn-relay
                PORTER_CLUSTER: "5534"
                PORTER_DEPLOYMENT_TARGET_ID: d60e67f5-b0a6-4275-8ed6-3cebaf092147
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PROJECT: "18525"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_18525_975734319 }}
